#!/bin/sh

# 
# Designed for EC2 instances, it will create a 2GB swap partition in 
# /media/ephemeral0/swapfile if there is no swap. Only the m1.small
# and c1.medium instances have swap partitions that are available
# automatically. All other instance types will have no default swap
# available. 
#
# For t1.small instances it will exist on the EBS volume under the
# same location. For everything else other than m1.small and c1.medium
# the swap will be a 2GB swap file.
#

if [ $EUID -ne 0 ]; then
    echo "ERROR: You must run this script as root"
    exit 1
fi

BASE="/media/ephemeral0"
SWAPFILE="$BASE/swapfile"

# Detect if swap currently exists
# for m1.small and c1.medium an ephemeral swap parition is
# automatically available
SWAP=$(swapon -s | grep '^/' | wc -l)
if [ $SWAP -gt 0 ]; then
    exit 0
fi

# just enable the swap if it exists and is the correct size
if [ -e $SWAPFILE ]; then
    if [ $(stat --terse $SWAPFILE | awk '{print $2}') -eq 2147483648 ]; then
        echo "Enabling swapfile: $SWAPFILE"
        swapon $SWAPFILE
        exit 0
    fi
fi

if [ ! -d $BASE ]; then
    echo "ERROR: $BASE does not exist. No where to create swapfile"
    exit 1
fi

echo "Creating 2GB Swap file at $SWAPFILE"

dd if=/dev/zero of=$SWAPFILE bs=4k count=524288
mkswap $SWAPFILE
swapon $SWAPFILE
